volumes:
  pgdata:

services:
  redis:
    image: redis:8
    ports:
      - 6379:6379
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ushort
